### ISSUE TITLE
TM Eclipse plugin should be signed so it doesn't give unsigned software warning at install

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TeamMentor_Eclipse_Plugin#16] opened 2013-10-21 10:00 UTC
![image](https://f.cloud.github.com/assets/1326120/1371316/a84a0138-3a37-11e3-88a0-23feeaa09333.png)

**Comment by DinisCruz** [comment] 2013-10-22 14:53
I'm 90% there with the build automation using maven, tycho and SWTbot and this is something that I will add to it (see https://github.com/TeamMentor/TeamMentor_Eclipse_Plugin/issues/5 )

**Comment by romichg** [comment] 2013-10-25 07:49
Probably we can live with this for Beta?

**Comment by DinisCruz** [comment] 2013-10-26 04:12
OK, I figured out how to do this, but at the moment I'm using a self-signed cert (since we have not bough one for TM), which will look like this:

![screen shot 2013-10-26 at 05 07 18](https://f.cloud.github.com/assets/656739/1412855/848dd876-3df4-11e3-8f06-d34b6b0227a8.png)

with these TM/SI values

![image](https://f.cloud.github.com/assets/656739/1412858/98515b26-3df4-11e3-8b34-d7b1fca82f66.png)

For reference the first version that was signed was the 

```
feature url="features/TeamMentor.Feature_1.3.3.201310260436.jar" 
id="TeamMentor.Feature" 
version="1.3.3.201310260436"
```

**Comment by DinisCruz** [comment] 2013-10-26 04:36
Hummm, it looks like I'm hitting on the problem described here: http://swdevadventures.blogspot.co.uk/2011/09/signing-eclipse-plugin-with-java-7.html

where in some installs of Eclipse (it seems to depend on the config and os combination), we get this error:

![image](https://f.cloud.github.com/assets/656739/1412875/edf68486-3df7-11e3-8da9-4c4a6dd16122.png)

Roman, can you reproduce this (i.e. can you see in some cases the better cert window and in others the build fail)

**Comment by DinisCruz** [comment] 2013-10-26 04:45
I just created a new version with the SHA1withRSA proposed fixed (referenced article above) and the version 1.3.3.201310260436 seems to install ok

**Comment by DinisCruz** [comment] 2013-10-26 05:38
Ok, I think this is solid now, I just pushed the 1.3.4 version and it installed OK on: 32 and 64bit on a variation of OSX, Linux and Windows (testing both clean install and upgrade scenarios), and I have not seen the error shown above.

Btw, note that you need to click on the checkbox that says 'Trust this certificate' since if you don't nothing happens (i.e. the install/upgrade fails silently (that is an Eclipse thing))

As per the current workflow, I'm closing the issue here, and leaving it open at https://github.com/TeamMentor/Master/issues/646

**Closed as completed by DinisCruz** 2013-10-26 05:38 UTC
